Increased minimum version of pluggy package to accomodate Python 3.8
Details:

* Increased minimum version of pluggy package from 0.12.0 to 0.13.0
  because it failed on python 3.8 (and only there) during loading of
  pytest plugins with:

    found = cls._search_paths(context.pattern, context.path)
    AttributeError: 'str' object has no attribute 'pattern'

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>