Pinned Pygments to <2.4.0 and readme-renderer to <25.0 for Python 3.4 support
Details:

* Pygments 2.4.0 (used by Sphinx) and readme-renderer 25.0 (used by twine)
  have removed support for Python 3.4. The Pygments change happened already
  in 5/2019 and was covered by Pip's ability to take the Python version
  into account when installing the latest version of a package. However,
  this ability does not cover upgrading already installed packages, and
  so the issue surfaced when the installation of twine required readme-renderer
  25.0 which required Pygments>=2.5.1 and along with Sphinx, Pygments 2.3.1
  had already been installed. the error was:

    ERROR: readme-renderer 25.0 has requirement Pygments>=2.5.1, but you'll
    have pygments 2.3.1 which is incompatible.

  As a solution, pinned the versions of Pygments and readme-renderer to
  below these versions on Python 3.4.

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>